DryFruitSelling/Controllers/LogisticsController.cs
using DryFruitSelling.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DryFruitSelling.Controllers
{
    public class LogisticsController : Controller
    {

        string strcon = ConfigurationManager.ConnectionStrings["MyConnection"].ConnectionString;

        // GET: Logistics
        public ActionResult Index()
        {
            List<LogisticsModel> logistic = new List<LogisticsModel>();
            using (SqlConnection conn = new SqlConnection(strcon))
            {
                conn.Open();
                SqlCommand cmd = new SqlCommand("usp_vwall_Logistics", conn);
                cmd.CommandType = System.Data.CommandType.StoredProcedure;

                SqlDataReader sdr = cmd.ExecuteReader();
                while(sdr.Read())
                {
                    logistic.Add(new LogisticsModel
                    {
                        id = Convert.ToInt32(sdr["id"]),
                        ShipmentID = sdr["ShipmentID"].ToString(),
                        FruitType = sdr["FruitType"].ToString(),
                        Quantity = Convert.ToInt32(sdr["Quantity"]),
                        Destination = sdr["Destination"].ToString(),
                        ShipmentDate = Convert.ToDateTime(sdr["ShipmentDate"]),
                        DeliveryStatus = sdr["DeliveryStatus"].ToString()
                    });
                }

                conn.Close();
            }

                return View(logistic);
        }



        private LogisticsModel objDetails(int id)
        {

            LogisticsModel logistic = new LogisticsModel();
            using (SqlConnection conn = new SqlConnection(strcon))
            {
                conn.Open();
                SqlCommand cmd = new SqlCommand("usp_vwone_Logistics", conn);
                cmd.CommandType = System.Data.CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@id", id);
                SqlDataReader sdr = cmd.ExecuteReader();
                while (sdr.Read())
                {
                    logistic = new LogisticsModel
                    {
                        id = Convert.ToInt32(sdr["id"]),
                        ShipmentID = sdr["ShipmentID"].ToString(),
                        FruitType = sdr["FruitType"].ToString(),
                        Quantity = Convert.ToInt32(sdr["Quantity"]),
                        Destination = sdr["Destination"].ToString(),
                        ShipmentDate = Convert.ToDateTime(sdr["ShipmentDate"]),
                        DeliveryStatus = sdr["DeliveryStatus"].ToString()
                    };
                }

                conn.Close();
            }

            return logistic;



        }

        // GET: Logistics/Details/5
        public ActionResult Details(int id)
        {
            return View(objDetails(id));
        }

        // GET: Logistics/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Logistics/Create
        [HttpPost]
        public ActionResult Create(LogisticsModel logistic)
        {
            try
            {
                // TODO: Add insert logic here
                using(SqlConnection conn = new SqlConnection(strcon))
                {
                    conn.Open();
                    SqlCommand cmd = new SqlCommand("usp_insert_logistics", conn);
                    cmd.CommandType = System.Data.CommandType.StoredProcedure;

                    cmd.Parameters.AddWithValue("@ShipmentID", logistic.ShipmentID);
                    cmd.Parameters.AddWithValue("@FruitType", logistic.FruitType);
                    cmd.Parameters.AddWithValue("@Quantity", logistic.Quantity);
                    cmd.Parameters.AddWithValue("@Destination", logistic.Destination);
                    cmd.Parameters.AddWithValue("@ShipmentDate", logistic.ShipmentDate);
                    cmd.Parameters.AddWithValue("@DeliveryStatus", logistic.DeliveryStatus);

                    int i = cmd.ExecuteNonQuery();
                    if(i>0)
                    {
                        TempData["Success"] = "Data Send Successfully!";
                    }
                    else
                    {
                        TempData["Error"] = "Data Send Failure!";
                    }

                    conn.Close();
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Logistics/Edit/5
        public ActionResult Edit(int id)
        {
            return View(objDetails(id));
        }

        // POST: Logistics/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, LogisticsModel logistic)
        {
            try
            {
                // TODO: Add update logic here
                using (SqlConnection conn = new SqlConnection(strcon))
                {
                    conn.Open();
                    SqlCommand cmd = new SqlCommand("usp_update_logistics", conn);
                    cmd.CommandType = System.Data.CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@id", id);
                    cmd.Parameters.AddWithValue("@ShipmentID", logistic.ShipmentID);
                    cmd.Parameters.AddWithValue("@FruitType", logistic.FruitType);
                    cmd.Parameters.AddWithValue("@Quantity", logistic.Quantity);
                    cmd.Parameters.AddWithValue("@Destination", logistic.Destination);
                    cmd.Parameters.AddWithValue("@ShipmentDate", logistic.ShipmentDate);
                    cmd.Parameters.AddWithValue("@DeliveryStatus", logistic.DeliveryStatus);

                    int i = cmd.ExecuteNonQuery();
                    if (i > 0)
                    {
                        TempData["Success"] = "Data update Successfully!";
                    }
                    else
                    {
                        TempData["Error"] = "Data update Failure!";
                    }

                    conn.Close();
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Logistics/Delete/5
        public ActionResult Delete(int id)
        {
            return View(objDetails(id));
        }

        // POST: Logistics/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                using (SqlConnection conn = new SqlConnection(strcon))
                {
                    conn.Open();
                    SqlCommand cmd = new SqlCommand("usp_delete_Logistics", conn);
                    cmd.CommandType = System.Data.CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@id", id);
                    
                    int i = cmd.ExecuteNonQuery();
                    if (i > 0)
                    {
                        TempData["Success"] = "Data Delete Successfully!";
                    }
                    else
                    {
                        TempData["Error"] = "Data Delete Failure!";
                    }

                    conn.Close();
                }


                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }




        public ActionResult Search()
        {
            List<LogisticsModel> logistic = new List<LogisticsModel>();
            using (SqlConnection conn = new SqlConnection(strcon))
            {
                conn.Open();
                SqlCommand cmd = new SqlCommand("usp_vwall_Logistics", conn);
                cmd.CommandType = System.Data.CommandType.StoredProcedure;

                SqlDataReader sdr = cmd.ExecuteReader();
                while (sdr.Read())
                {
                    logistic.Add(new LogisticsModel
                    {
                        id = Convert.ToInt32(sdr["id"]),
                        ShipmentID = sdr["ShipmentID"].ToString(),
                        FruitType = sdr["FruitType"].ToString(),
                        Quantity = Convert.ToInt32(sdr["Quantity"]),
                        Destination = sdr["Destination"].ToString(),
                        ShipmentDate = Convert.ToDateTime(sdr["ShipmentDate"]),
                        DeliveryStatus = sdr["DeliveryStatus"].ToString()
                    });
                }

                conn.Close();
            }

            return View(logistic);
        }


        [HttpPost]
        public ActionResult Search(string Search)
        {
            List<LogisticsModel> logistic = new List<LogisticsModel>();
            using (SqlConnection conn = new SqlConnection(strcon))
            {
                conn.Open();
                SqlCommand cmd = new SqlCommand("usp_search_Logistics", conn);
                cmd.CommandType = System.Data.CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@Searchdata", Search);
                SqlDataReader sdr = cmd.ExecuteReader();
                while (sdr.Read())
                {
                    logistic.Add(new LogisticsModel
                    {
                        id = Convert.ToInt32(sdr["id"]),
                        ShipmentID = sdr["ShipmentID"].ToString(),
                        FruitType = sdr["FruitType"].ToString(),
                        Quantity = Convert.ToInt32(sdr["Quantity"]),
                        Destination = sdr["Destination"].ToString(),
                        ShipmentDate = Convert.ToDateTime(sdr["ShipmentDate"]),
                        DeliveryStatus = sdr["DeliveryStatus"].ToString()

DryFruitSelling/Views/Logistics/Create.cshtml
@model DryFruitSelling.Models.LogisticsModel

<main class="flex-shrink-0">
    <section class="py-5">
        <div class="container px-5">
            <!-- Contact form-->
            <div class="bg-light rounded-3 py-5 px-4 px-md-5 mb-5">
                <div class="text-center mb-5">
                    <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-person-circle"></i></div>


                    <h1 class="fw-bolder">Create Logistic System Details</h1>

                </div>
                <div class="row gx-5 justify-content-center">
                    <div class="col-lg-8 col-xl-6">

                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">

                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                                <div class="form-group mt-2 mb-3">
                                    @Html.LabelFor(model => model.ShipmentID, htmlAttributes: new { @class = "control-label" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.ShipmentID, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.ShipmentID, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group mb-3">
                                    @Html.LabelFor(model => model.FruitType, htmlAttributes: new { @class = "control-label" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.FruitType, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.FruitType, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group mb-3">
                                    @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group mb-3">
                                    @Html.LabelFor(model => model.Destination, htmlAttributes: new { @class = "control-label" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Destination, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Destination, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group mb-3">
                                    @Html.LabelFor(model => model.ShipmentDate, htmlAttributes: new { @class = "control-label" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.ShipmentDate, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.ShipmentDate, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group mb-3">
                                    @Html.LabelFor(model => model.DeliveryStatus, htmlAttributes: new { @class = "control-label" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.DeliveryStatus, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.DeliveryStatus, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group mb-3">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="submit" value="Create" class="btn btn-primary" />
                                    </div>
                                </div>
                            </div>
                        }

                        <div>
                            @Html.ActionLink("Back to List", "Index")
                        </div>





                    </div>
                </div>
            </div>
        </div>
    </section>
</main>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DryFruitSelling/Views/Logistics/Delete.cshtml
@model DryFruitSelling.Models.LogisticsModel
<main class="flex-shrink-0">
    <section class="py-5">
        <div class="container px-5">
            <!-- Contact form-->
            <div class="bg-light rounded-3 py-5 px-4 px-md-5 mb-5">
                <div class="text-center mb-5">
                    <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-person-circle"></i></div>


                    <h1 class="fw-bolder">Delete Logistic System Details</h1>

                </div>
                <div class="row gx-5 justify-content-center">
                    <div class="col-lg-8 col-xl-6">

                        <h3>Are you sure you want to delete this?</h3>
                        <div>

                            <dl class="dl-horizontal">
                                <dt>
                                    @Html.DisplayNameFor(model => model.ShipmentID)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.ShipmentID)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.FruitType)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.FruitType)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.Quantity)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Quantity)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.Destination)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Destination)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.ShipmentDate)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.ShipmentDate)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.DeliveryStatus)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.DeliveryStatus)
                                </dd>

                            </dl>

                            @using (Html.BeginForm())
                            {
                                @Html.AntiForgeryToken()

                                <div class="form-actions no-color">
                                    <input type="submit" value="Delete" class="btn btn-danger" /> |
                                    @Html.ActionLink("Back to List", "Index")
                                </div>
                            }
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
</main>

DryFruitSelling/Views/Logistics/Details.cshtml
@model DryFruitSelling.Models.LogisticsModel
<main class="flex-shrink-0">
    <section class="py-5">
        <div class="container px-5">
            <!-- Contact form-->
            <div class="bg-light rounded-3 py-5 px-4 px-md-5 mb-5">
                <div class="text-center mb-5">
                    <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-person-circle"></i></div>


                    <h1 class="fw-bolder">Logistic System Details</h1>

                </div>
                <div class="row gx-5 justify-content-center">
                    <div class="col-lg-8 col-xl-6">


                        <div>

                            <dl class="dl-horizontal">
                                <dt>
                                    @Html.DisplayNameFor(model => model.ShipmentID)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.ShipmentID)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.FruitType)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.FruitType)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.Quantity)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Quantity)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.Destination)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Destination)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.ShipmentDate)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.ShipmentDate)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.DeliveryStatus)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.DeliveryStatus)
                                </dd>

                            </dl>
                        </div>
                        <p>
                            @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
                            @Html.ActionLink("Back to List", "Index")
                        </p>

                    </div>
                </div>
            </div>
        </div>
    </section>
</main>

DryFruitSelling/Views/Logistics/Edit.cshtml
@model DryFruitSelling.Models.LogisticsModel

<main class="flex-shrink-0">
    <section class="py-5">
        <div class="container px-5">
            <!-- Contact form-->
            <div class="bg-light rounded-3 py-5 px-4 px-md-5 mb-5">
                <div class="text-center mb-5">
                    <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-person-circle"></i></div>


                    <h1 class="fw-bolder">Edit Logistic System Details</h1>

                </div>
                <div class="row gx-5 justify-content-center">
                    <div class="col-lg-8 col-xl-6">

                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">

                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                @Html.HiddenFor(model => model.id)

                                <div class="form-group mt-2 mb-3">
                                    @Html.LabelFor(model => model.ShipmentID, htmlAttributes: new { @class = "control-label" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.ShipmentID, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.ShipmentID, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group mb-3">
                                    @Html.LabelFor(model => model.FruitType, htmlAttributes: new { @class = "control-label" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.FruitType, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.FruitType, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group mb-3">
                                    @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group mb-3">
                                    @Html.LabelFor(model => model.Destination, htmlAttributes: new { @class = "control-label" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Destination, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Destination, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group mb-3">
                                    @Html.LabelFor(model => model.ShipmentDate, htmlAttributes: new { @class = "control-label" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.ShipmentDate, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.ShipmentDate, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group mb-3">
                                    @Html.LabelFor(model => model.DeliveryStatus, htmlAttributes: new { @class = "control-label" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.DeliveryStatus, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.DeliveryStatus, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group mb-3">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="submit" value="Save" class="btn btn-primary" />
                                    </div>
                                </div>
                            </div>
                        }

                        <div>
                            @Html.ActionLink("Back to List", "Index")
                        </div>





                    </div>
                </div>
            </div>
        </div>
    </section>
</main>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DryFruitSelling/Views/Logistics/Index.cshtml
@model IEnumerable<DryFruitSelling.Models.LogisticsModel>



@if (TempData["Success"] != null)
{
    <script>alert("@TempData["Success"]")</script>
}




@if (TempData["Error"] != null)
{
    <script>alert("@TempData["Error"]")</script>
}


<div class="p-3 mb-2 bg-secondary text-white text-center mt-5 mb-5">
    Logistics Record Details

</div>

<p>
    @Html.ActionLink("Create New", "Create")

    &nbsp;&nbsp;&nbsp;&nbsp;

    @Html.ActionLink("Search", "Search")


</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ShipmentID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FruitType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Destination)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ShipmentDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DeliveryStatus)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ShipmentID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FruitType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Destination)
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.ShipmentDate)*@
                @item.ShipmentDate.ToString("dd/MM/yyyy")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DeliveryStatus)
            </td>
            <td>
                <div class="btn-group" role="group" aria-label="Basic mixed styles example">


                    @using (Html.BeginForm("Edit", "Logistics", new { id = item.id }, FormMethod.Get, new { @class = "form-inline" }))
                    {
                        <button class="btn btn-warning" type="submit">Edit</button>
                    }

                    &nbsp;

                    @using (Html.BeginForm("Details", "Logistics", new { id = item.id }, FormMethod.Get, new { @class = "form-inline" }))
                    {
                        <button class="btn btn-primary" type="submit">Details</button>
                    }

                    &nbsp;

                    @using (Html.BeginForm("Delete", "Logistics", new { id = item.id }, FormMethod.Get, new { @class = "form-inline" }))
                    {
                        <button class="btn btn-danger" type="submit">Delete</button>
                    }




                </div>
            </td>
        </tr>
    }

</table>