DryFruitSelling/Models/Supplier.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DryFruitSelling.Models
{
    public class Supplier
    {

        public int id {  get; set; }

        [Required]
        [Display(Name ="Supplier ID")]
        public string SupplierID { get; set; }

        [Required]
        [Display(Name = "Suplier Nmae")]
        public string SupplierName {  get; set; }


        [Required]
        [Display(Name = "Contact Number")]
        public string ContactNumber { get; set; }


        [Required]
        [Display(Name = "Address")]
        public string Address { get; set; }



        [Required]
        [Display(Name = "Order History")]
        public string OrderHistory { get; set; }




    }
}

DryFruitSelling/Controllers/SupplierController.cs
using DryFruitSelling.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace DryFruitSelling.Controllers
{
    public class SupplierController : Controller
    {


        string strcon = ConfigurationManager.ConnectionStrings["MyConnection"].ConnectionString;


        
        
        // GET: Supplier
        public ActionResult Index()
        {
            List<Supplier>  suppliers = new List<Supplier>();
            using(SqlConnection conn = new SqlConnection(strcon))
            {
                conn.Open();
                SqlCommand cmd = new SqlCommand("sp_vwall_supplier", conn);
                cmd.CommandType = System.Data.CommandType.StoredProcedure;

                SqlDataReader sdr= cmd.ExecuteReader();
                while(sdr.Read())
                {
                    suppliers.Add(new Supplier
                    {
                        id =Convert.ToInt32(sdr["id"]),
                        SupplierID = sdr["SupplierID"].ToString(),
                        SupplierName = sdr["SupplierName"].ToString(),
                        ContactNumber = sdr["ContactNumber"].ToString(),
                        Address = sdr["Address"].ToString(),
                        OrderHistory = sdr["OrderHistory"].ToString()

                    });
                }
                conn.Close();
            }


            return View(suppliers);
        }

       


        
        
        // GET: Supplier/Details/5
        public ActionResult Details(int id)
        {
            Supplier suppliers = new Supplier();
            using (SqlConnection conn = new SqlConnection(strcon))
            {
                conn.Open();
                SqlCommand cmd = new SqlCommand("sp_getone_supplier", conn);
                cmd.CommandType = System.Data.CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@id", id);
                SqlDataReader sdr = cmd.ExecuteReader();
                while (sdr.Read())
                {
                    suppliers = new Supplier
                    {
                        id = Convert.ToInt32(sdr["id"]),
                        SupplierID = sdr["SupplierID"].ToString(),
                        SupplierName = sdr["SupplierName"].ToString(),
                        ContactNumber = sdr["ContactNumber"].ToString(),
                        Address = sdr["Address"].ToString(),
                        OrderHistory = sdr["OrderHistory"].ToString()

                    };


                }
                conn.Close();

            }


            return View(suppliers);
        }

        




        
        // GET: Supplier/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Supplier/Create
        [HttpPost]
        public ActionResult Create(Supplier suppliers)
        {
            try
            {
                // TODO: Add insert logic here
                using (SqlConnection conn = new SqlConnection(strcon))
                {
                    conn.Open();
                    SqlCommand cmd = new SqlCommand("usp_insert_supplier", conn);
                    cmd.CommandType = System.Data.CommandType.StoredProcedure;

                    cmd.Parameters.AddWithValue("@SupplierID", suppliers.SupplierID);
                    cmd.Parameters.AddWithValue("@SupplierName", suppliers.SupplierName);
                    cmd.Parameters.AddWithValue("@ContactNumber", suppliers.ContactNumber);
                    cmd.Parameters.AddWithValue("@Address", suppliers.Address);
                    cmd.Parameters.AddWithValue("@OrderHistory", suppliers.OrderHistory);

                     int i = cmd.ExecuteNonQuery();
                    
                    if (i > 0) 
                    {
                        TempData["Success"] = "Data send successfully!";  
                    
                    }
                    else
                    {
                        TempData["Error"] = "Data send Failure!";
                    }


                }
                    return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }










        // GET: Supplier/Edit/5
        public ActionResult Edit(int id)
        {

            Supplier suppliers = new Supplier();
            using (SqlConnection conn = new SqlConnection(strcon))
            {
                conn.Open();
                SqlCommand cmd = new SqlCommand("sp_getone_supplier", conn);
                cmd.CommandType = System.Data.CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@id", id);
                SqlDataReader sdr = cmd.ExecuteReader();
                while (sdr.Read())
                {
                    suppliers = new Supplier
                    {
                        id = Convert.ToInt32(sdr["id"]),
                        SupplierID = sdr["SupplierID"].ToString(),
                        SupplierName = sdr["SupplierName"].ToString(),
                        ContactNumber = sdr["ContactNumber"].ToString(),
                        Address = sdr["Address"].ToString(),
                        OrderHistory = sdr["OrderHistory"].ToString()

                    };
                }
                conn.Close();
            }


            return View(suppliers);
        }






        // POST: Supplier/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Supplier suppliers)
        {
            try
            {
                // TODO: Add update logic here
                using (SqlConnection conn = new SqlConnection(strcon))
                {
                    conn.Open();
                    SqlCommand cmd = new SqlCommand("usp_update_supplier", conn);
                    cmd.CommandType = System.Data.CommandType.StoredProcedure;

                    cmd.Parameters.AddWithValue("@id",id);
                    cmd.Parameters.AddWithValue("@SupplierID", suppliers.SupplierID);
                    cmd.Parameters.AddWithValue("@SupplierName", suppliers.SupplierName);
                    cmd.Parameters.AddWithValue("@ContactNumber", suppliers.ContactNumber);
                    cmd.Parameters.AddWithValue("@Address", suppliers.Address);
                    cmd.Parameters.AddWithValue("@OrderHistory", suppliers.OrderHistory);

                    int i = cmd.ExecuteNonQuery();
                    if (i > 0)
                    {
                        TempData["Success"] = "Data Updated successfully!";


                    }
                    else
                    {
                        TempData["Error"] = "Data Updated Failure!";

                    }


                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }







        // GET: Supplier/Delete/5
        public ActionResult Delete(int id)
        {

            Supplier suppliers = new Supplier();
            using (SqlConnection conn = new SqlConnection(strcon))
            {
                conn.Open();
                SqlCommand cmd = new SqlCommand("sp_getone_supplier", conn);
                cmd.CommandType = System.Data.CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@id", id);
                SqlDataReader sdr = cmd.ExecuteReader();
                while (sdr.Read())
                {
                    suppliers = new Supplier
                    {
                        id = Convert.ToInt32(sdr["id"]),
                        SupplierID = sdr["SupplierID"].ToString(),
                        SupplierName = sdr["SupplierName"].ToString(),
                        ContactNumber = sdr["ContactNumber"].ToString(),
                        Address = sdr["Address"].ToString(),
                        OrderHistory = sdr["OrderHistory"].ToString()

                    };
                }
                conn.Close();
            }


            return View(suppliers);
        }









        // POST: Supplier/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                using (SqlConnection conn = new SqlConnection(strcon))
                {
                    conn.Open();
                    SqlCommand cmd = new SqlCommand("sp_delete_supplier", conn);
                    cmd.CommandType = System.Data.CommandType.StoredProcedure;

                    cmd.Parameters.AddWithValue("@id", id);
                    
                    int i = cmd.ExecuteNonQuery();
                    if (i > 0)
                    {
                        TempData["Success"] = "Data Deleted successfully!";


                    }
                    else
                    {
                        TempData["Error"] = "Data Deleted Failure!";

                    }


                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }







        public ActionResult Search()
        {
            List<Supplier> suppliers = new List<Supplier>();
            using (SqlConnection conn = new SqlConnection(strcon))
            {
                conn.Open();
                SqlCommand cmd = new SqlCommand("sp_vwall_supplier", conn);
                cmd.CommandType = System.Data.CommandType.StoredProcedure;

                SqlDataReader sdr = cmd.ExecuteReader();
                while (sdr.Read())
                {
                    suppliers.Add(new Supplier
                    {
                        id = Convert.ToInt32(sdr["id"]),
                        SupplierID = sdr["SupplierID"].ToString(),

DryFruitSelling/Views/Supplier/Create.cshtml
@model DryFruitSelling.Models.Supplier

@{
    ViewBag.Title = "Create";
}

<main class="flex-shrink-0">
    <section class="py-5">
        <div class="container px-5">
            <!-- Contact form-->
            <div class="bg-light rounded-3 py-5 px-4 px-md-5 mb-5">
                <div class="text-center mb-5">
                    <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-person-circle"></i></div>


                    <h1 class="fw-bolder">Create Supplier Details</h1>

                </div>
                <div class="row gx-5 justify-content-center">
                    <div class="col-lg-8 col-xl-6">


                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">

                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })




                                <div class="form-group mt-2 mb-3">
                                    @Html.LabelFor(model => model.SupplierID, htmlAttributes: new { @class = "control-label" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.SupplierID, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.SupplierID, "", new { @class = "text-danger" })
                                    </div>
                                </div>



                                <div class="form-group mb-3">
                                    @Html.LabelFor(model => model.SupplierName, htmlAttributes: new { @class = "control-label" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.SupplierName, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.SupplierName, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group mb-3">
                                    @Html.LabelFor(model => model.ContactNumber, htmlAttributes: new { @class = "control-label" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.ContactNumber, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.ContactNumber, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group mb-3">
                                    @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group mb-3">
                                    @Html.LabelFor(model => model.OrderHistory, htmlAttributes: new { @class = "control-label" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.OrderHistory, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.OrderHistory, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group mb-3">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="submit" value="Create" class="btn btn-primary" />
                                    </div>
                                </div>






                            </div>
                        }

                        <div>
                            @Html.ActionLink("Back to List", "Index")
                        </div>




                    </div>
                </div>
            </div>
        </div>
    </section>
</main>





@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DryFruitSelling/Views/Supplier/Delete.cshtml
@model DryFruitSelling.Models.Supplier

@{
    ViewBag.Title = "Delete";
}

<main class="flex-shrink-0">
    <section class="py-5">
        <div class="container px-5">
            <!-- Contact form-->
            <div class="bg-light rounded-3 py-5 px-4 px-md-5 mb-5">
                <div class="text-center mb-5">
                    <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-person-circle"></i></div>


                    <h1 class="fw-bolder">Delete Supplier Details</h1>

                </div>
                <div class="row gx-5 justify-content-center">
                    <div class="col-lg-8 col-xl-6">


                        <h3>Are you sure you want to delete this?</h3>
                        <div>

                            <dl class="dl-horizontal">

                                <dt>
                                    @Html.DisplayNameFor(model => model.SupplierID)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.SupplierID)
                                </dd>



                                <dt>
                                    @Html.DisplayNameFor(model => model.SupplierName)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.SupplierName)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.ContactNumber)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.ContactNumber)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.Address)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Address)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.OrderHistory)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.OrderHistory)
                                </dd>

                            </dl>

                            @using (Html.BeginForm())
                            {
                                @Html.AntiForgeryToken()

                                <div class="form-actions no-color">
                                    <input type="submit" value="Delete" class="btn btn-danger" /> |
                                    @Html.ActionLink("Back to List", "Index")
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>

DryFruitSelling/Views/Supplier/Details.cshtml
@model DryFruitSelling.Models.Supplier

@{
    ViewBag.Title = "Details";
}


<main class="flex-shrink-0">
    <section class="py-5">
        <div class="container px-5">
            <!-- Contact form-->
            <div class="bg-light rounded-3 py-5 px-4 px-md-5 mb-5">
                <div class="text-center mb-5">
                    <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-person-circle"></i></div>


                    <h1 class="fw-bolder">Supplier Details</h1>

                </div>
                <div class="row gx-5 justify-content-center">
                    <div class="col-lg-8 col-xl-6">

                        <div>
                            <dl class="dl-horizontal">


                                <dt>
                                    @Html.DisplayNameFor(model => model.SupplierID)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.SupplierID)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.SupplierName)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.SupplierName)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.ContactNumber)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.ContactNumber)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.Address)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Address)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.OrderHistory)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.OrderHistory)
                                </dd>

                            </dl>
                        </div>
                        <p>
                            @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
                            @Html.ActionLink("Back to List", "Index")
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>

DryFruitSelling/Views/Supplier/Edit.cshtml
@model DryFruitSelling.Models.Supplier

@{
    ViewBag.Title = "Edit";
}

<main class="flex-shrink-0">
    <section class="py-5">
        <div class="container px-5">
            <!-- Contact form-->
            <div class="bg-light rounded-3 py-5 px-4 px-md-5 mb-5">
                <div class="text-center mb-5">
                    <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-person-circle"></i></div>


                    <h1 class="fw-bolder">Edit Supplier Details</h1>

                </div>
                <div class="row gx-5 justify-content-center">
                    <div class="col-lg-8 col-xl-6">


                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">

                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                @Html.HiddenFor(model => model.id)

                                @*@Html.HiddenFor(model => model.SupplierID)*@




                                <div class="form-group mt-2 mb-3">
                                    @Html.LabelFor(model => model.SupplierID, htmlAttributes: new { @class = "control-label" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.SupplierID, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.SupplierID, "", new { @class = "text-danger" })
                                    </div>
                                </div>





                                <div class="form-group mb-3">
                                    @Html.LabelFor(model => model.SupplierName, htmlAttributes: new { @class = "control-label" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.SupplierName, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.SupplierName, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group mb-3">
                                    @Html.LabelFor(model => model.ContactNumber, htmlAttributes: new { @class = "control-label" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.ContactNumber, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.ContactNumber, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group mb-3">
                                    @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group mb-3">
                                    @Html.LabelFor(model => model.OrderHistory, htmlAttributes: new { @class = "control-label" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.OrderHistory, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.OrderHistory, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group mb-3">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="submit" value="Save" class="btn btn-primary" />
                                    </div>
                                </div>
                            </div>
                        }

                        <div>
                            @Html.ActionLink("Back to List", "Index")
                        </div>



                    </div>
                </div>
            </div>
        </div>
    </section>
</main>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DryFruitSelling/Views/Supplier/Index.cshtml
@model IEnumerable<DryFruitSelling.Models.Supplier>

@{
    ViewBag.Title = "Index";
}





@if (TempData["Success"] != null)
{
    <script style="color:green">
                        alert("@TempData["Success"]")

    </script>
}

@if (TempData["Error"] != null)
{
    <script style="color:indianred">
                        alert("@TempData["Error"]")

    </script>
}






<div class="p-3 mb-2 bg-secondary text-white text-center mt-5 mb-5">
    Supplier Record Details

</div>



<p>
    @Html.ActionLink("Create New", "Create")

    &nbsp;&nbsp;&nbsp;&nbsp;

    @Html.ActionLink("Search", "Search")
</p>
<table class="table">
    <tr>


        <th>
            @Html.DisplayNameFor(model => model.SupplierID)
        </th>


        <th>
            @Html.DisplayNameFor(model => model.SupplierName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ContactNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderHistory)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>


            <td>
                @Html.DisplayFor(modelItem => item.SupplierID)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.SupplierName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ContactNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrderHistory)
            </td>
            <td>
                <div class="btn-group" role="group" aria-label="Basic mixed styles example">


                    @using (Html.BeginForm("Edit", "Supplier", new { id = item.id }, FormMethod.Get, new { @class = "form-inline" }))
                    {
                        <button class="btn btn-warning" type="submit">Edit</button>
                    }

                    &nbsp;

                    @using (Html.BeginForm("Details", "Supplier", new { id = item.id }, FormMethod.Get, new { @class = "form-inline" }))
                    {
                        <button class="btn btn-primary" type="submit">Details</button>
                    }

                    &nbsp;

                    @using (Html.BeginForm("Delete", "Supplier", new { id = item.id }, FormMethod.Get, new { @class = "form-inline" }))
                    {
                        <button class="btn btn-danger" type="submit">Delete</button>
                    }




                </div>
            </td>
        </tr>
    }

</table>

DryFruitSelling/Views/Supplier/Search.cshtml
@model IEnumerable<DryFruitSelling.Models.Supplier>

@{
    ViewBag.Title = "Search";
}



<div class="p-3 mb-2 bg-secondary text-white text-center mt-5 mb-5">
    Supplier Record Details

</div>



<p>
    @Html.ActionLink("Go To Index", "Index")
</p>




@using (Html.BeginForm())
{

    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="offset-5 text-dark mb-5">
        <div class="form-group">
            <label for="Search">Search Supplier Details</label>
            <input type="search" class="form-control" name="Search" placeholder="Search Supplier Details" />
        </div>


        <div class="form-group mt-2">

            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Search" class="btn btn-success" />
            </div>


        </div>

    </div>
}




<table class="table">
    <tr>



        <th>
            @Html.DisplayNameFor(model => model.SupplierID)
        </th>


        <th>
            @Html.DisplayNameFor(model => model.SupplierName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ContactNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderHistory)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.SupplierID)
            </td>


            <td>
                @Html.DisplayFor(modelItem => item.SupplierName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ContactNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrderHistory)
            </td>
            <td>
                @*@Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })*@
            </td>
        </tr>
    }

</table>