DryFruitSelling/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DryFruitSelling.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

DryFruitSelling/Controllers/HomePageController.cs
using DryFruitSelling.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DryFruitSelling.Controllers
{
    public class HomePageController : Controller
    {
        string strcon = ConfigurationManager.ConnectionStrings["MyConnection"].ConnectionString;


        // GET: HomePage
        public ActionResult Home()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Home(string a)
        {

            return View();
        }



        public ActionResult AboutPage()
        {
            return View();
        }


        [HttpPost]
        public ActionResult AboutPage(string a)
        {

            return View();
        }




        public ActionResult ContactPage()
        {
            return View();
        }


        [HttpPost]
        public ActionResult ContactPage(contactus contact)
        {

            try
            {
                // TODO: Add insert logic here
                using (SqlConnection conn = new SqlConnection(strcon))
                {
                    conn.Open();
                    SqlCommand cmd = new SqlCommand("sp_insert_contactus", conn);
                    cmd.CommandType = System.Data.CommandType.StoredProcedure;

                    cmd.Parameters.AddWithValue("@Name", contact.Name);

                    cmd.Parameters.AddWithValue("@Email", contact.Email);
                    cmd.Parameters.AddWithValue("@Phone", contact.Phone);

                    cmd.Parameters.AddWithValue("@Message", contact.Message);


                    int i = cmd.ExecuteNonQuery();
                    if (i > 0)
                    {
                        TempData["Success"] = "Data Send Successfully!";
                    }
                    else
                    {
                        TempData["Error"] = "Data Send Failure!";
                    }

                    conn.Close();
                }

                return RedirectToAction("ContactPage");
            }
            catch
            {
                return View();
            }
        }




        public ActionResult ShopPage()
        {
            return View();
        }


        [HttpPost]
        public ActionResult ShopPage(string a)
        {

            return View();
        }


        public ActionResult UserPage()
        {
            return View();
        }


        [HttpPost]
        public ActionResult UserPage(string a)
        {

            return View();
        }


        public ActionResult AdminPage()
        {
            return View();
        }


        [HttpPost]
        public ActionResult AdminPage(string a)
        {

            return View();
        }













































    }
}

DryFruitSelling/Controllers/SalesController.cs
using DryFruitSelling.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DryFruitSelling.Controllers
{
    public class SalesController : Controller
    {
        string strcon = ConfigurationManager.ConnectionStrings["MyConnection"].ConnectionString;
        // GET: Sales
        public ActionResult Index()
        {
            List<SalesModel> sale = new List<SalesModel>();
            using(SqlConnection conn = new SqlConnection(strcon))
            {
                conn.Open();
                SqlCommand cmd = new SqlCommand("sp_vwall_sales", conn);
                cmd.CommandType = System.Data.CommandType.StoredProcedure;

                SqlDataReader sdr = cmd.ExecuteReader();
                while(sdr.Read())
                {
                    sale.Add(new SalesModel
                    { 
                    
                        id = Convert.ToInt32(sdr["id"]),
                        SaleID = sdr["SaleID"].ToString(),
                        CustomerID = sdr["CustomerID"].ToString(),
                        FruitType = sdr["FruitType"].ToString(),
                        Quantity = Convert.ToInt32(sdr["Quantity"]),
                        SaleDate = Convert.ToDateTime(sdr["SaleDate"]),
                        Revenue = Convert.ToDecimal(sdr["Revenue"])

                    });
                }
                conn.Close();
            }


            return View(sale);
        }



        private SalesModel objDetail(int id)
        {
            SalesModel sale = new SalesModel();
            using (SqlConnection conn = new SqlConnection(strcon))
            {
                conn.Open();
                SqlCommand cmd = new SqlCommand("sp_vwone_sales", conn);
                cmd.CommandType = System.Data.CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@id", id);
                SqlDataReader sdr = cmd.ExecuteReader();
                while (sdr.Read())
                {
                    sale = new SalesModel
                    {

                        id = Convert.ToInt32(sdr["id"]),
                        SaleID = sdr["SaleID"].ToString(),
                        CustomerID = sdr["CustomerID"].ToString(),
                        FruitType = sdr["FruitType"].ToString(),
                        Quantity = Convert.ToInt32(sdr["Quantity"]),
                        SaleDate = Convert.ToDateTime(sdr["SaleDate"]),
                        Revenue = Convert.ToDecimal(sdr["Revenue"])

                    };
                }
                conn.Close();
            }
            return sale; 
        }



        // GET: Sales/Details/5
        public ActionResult Details(int id)
        {


            return View(objDetail(id)); 
        }

        // GET: Sales/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Sales/Create
        [HttpPost]
        public ActionResult Create(SalesModel sale)
        {
            try
            {
                // TODO: Add insert logic here
                using (SqlConnection conn = new SqlConnection(strcon))
                {
                    conn.Open() ;
                    SqlCommand cmd = new SqlCommand("sp_insert_sales", conn);
                    cmd.CommandType = System.Data.CommandType.StoredProcedure;

                    cmd.Parameters.AddWithValue("@SaleID", sale.SaleID);
                    cmd.Parameters.AddWithValue("@CustomerID", sale.CustomerID);
                    cmd.Parameters.AddWithValue("@FruitType", sale.FruitType);
                    cmd.Parameters.AddWithValue("@Quantity", sale.Quantity);
                    cmd.Parameters.AddWithValue("@SaleDate", sale.SaleDate);
                    cmd.Parameters.AddWithValue("@Revenue", sale.Revenue);
                    int i = cmd.ExecuteNonQuery();

                    if(i>0)
                    {
                        TempData["Success"] = "Data Send successfully!";
                    }
                    else
                    {
                        TempData["Error"] = "Data Send Failure!";
                    }
                    conn.Close();
                }
                    return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Sales/Edit/5
        public ActionResult Edit(int id)
        {
            return View(objDetail(id));
        }

        // POST: Sales/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, SalesModel sale)
        {
            try
            {
                // TODO: Add update logic here
                using (SqlConnection conn = new SqlConnection(strcon))
                {
                    conn.Open();
                    SqlCommand cmd = new SqlCommand("sp_update_sales", conn);
                    cmd.CommandType = System.Data.CommandType.StoredProcedure;

                    cmd.Parameters.AddWithValue("@id", id);
                    cmd.Parameters.AddWithValue("@SaleID", sale.SaleID);
                    cmd.Parameters.AddWithValue("@CustomerID", sale.CustomerID);
                    cmd.Parameters.AddWithValue("@FruitType", sale.FruitType);
                    cmd.Parameters.AddWithValue("@Quantity", sale.Quantity);
                    cmd.Parameters.AddWithValue("@SaleDate", sale.SaleDate);
                    cmd.Parameters.AddWithValue("@Revenue", sale.Revenue);
                    int i = cmd.ExecuteNonQuery();

                    if (i > 0)
                    {
                        TempData["Success"] = "Data Updated successfully!";
                    }
                    else
                    {
                        TempData["Error"] = "Data Updated Failure!";
                    }
                    conn.Close();
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Sales/Delete/5
        public ActionResult Delete(int id)
        {
            return View(objDetail(id));
        }

        // POST: Sales/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                using (SqlConnection conn = new SqlConnection(strcon))
                {
                    conn.Open();
                    SqlCommand cmd = new SqlCommand("sp_delete_sales", conn);
                    cmd.CommandType = System.Data.CommandType.StoredProcedure;

                    cmd.Parameters.AddWithValue("@id", id);
                
                    
                    int i = cmd.ExecuteNonQuery();

                    if (i > 0)
                    {
                        TempData["Success"] = "Data Deleted successfully!";
                    }
                    else
                    {
                        TempData["Error"] = "Data Deleted Failure!";
                    }
                    conn.Close();
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }






        public ActionResult Search()
        {
            List<SalesModel> sale = new List<SalesModel>();
            using (SqlConnection conn = new SqlConnection(strcon))
            {
                conn.Open();
                SqlCommand cmd = new SqlCommand("sp_vwall_sales", conn);
                cmd.CommandType = System.Data.CommandType.StoredProcedure;

                SqlDataReader sdr = cmd.ExecuteReader();
                while (sdr.Read())
                {
                    sale.Add(new SalesModel
                    {

                        id = Convert.ToInt32(sdr["id"]),
                        SaleID = sdr["SaleID"].ToString(),
                        CustomerID = sdr["CustomerID"].ToString(),
                        FruitType = sdr["FruitType"].ToString(),
                        Quantity = Convert.ToInt32(sdr["Quantity"]),
                        SaleDate = Convert.ToDateTime(sdr["SaleDate"]),
                        Revenue = Convert.ToDecimal(sdr["Revenue"])

                    });
                }
                conn.Close();
            }


            return View(sale);
        }




        [HttpPost]
        public ActionResult Search(string Search)
        {
            List<SalesModel> sale = new List<SalesModel>();
            using (SqlConnection conn = new SqlConnection(strcon))
            {
                conn.Open();
                SqlCommand cmd = new SqlCommand("sp_search_sales", conn);
                cmd.CommandType = System.Data.CommandType.StoredProcedure;

                cmd.Parameters.AddWithValue("@Searchdata", Search);
                SqlDataReader sdr = cmd.ExecuteReader();
                while (sdr.Read())
                {
                    sale.Add(new SalesModel
                    {

                        id = Convert.ToInt32(sdr["id"]),
                        SaleID = sdr["SaleID"].ToString(),
                        CustomerID = sdr["CustomerID"].ToString(),
                        FruitType = sdr["FruitType"].ToString(),
                        Quantity = Convert.ToInt32(sdr["Quantity"]),
                        SaleDate = Convert.ToDateTime(sdr["SaleDate"]),
                        Revenue = Convert.ToDecimal(sdr["Revenue"])

                    });
                }
                conn.Close();
            }


            return View(sale);
        }























































    }
}

DryFruitSelling/Views/HomePage/AdminPage.cshtml
@{
    ViewBag.Title = "AdminPage";
}


<section>

    <center class="mt-5 mb-5">
        <h2 style="color:chocolate">Welcome To Admin Controls</h2>
    </center>



    <div class="container">
        <div class="row">

            <div class="col">

                <div class="card" style="width: 18rem;color:ghostwhite">

                    <div class="card-body" style="background-color: rgb(192, 78, 237) ">
                        <h5 class="card-title">Customer Information Details</h5>


                        @*linkName   ActionName    Controller*@
                        @Html.ActionLink("Customer Details", "Index", "Customer", new { area = "" }, new { @class = "btn btn-primary" })


                    </div>
                </div>
            </div>


            <div class="col">

                <div class="card" style="width: 18rem; color: ghostwhite">

                    <div class="card-body" style="background-color:rgb(192, 78, 237)">
                        <h5 class="card-title">Customer Support Management Details</h5>
                        @*linkName   ActionName    Controller*@
                        @Html.ActionLink("Customer Support Info", "Index", "CustSupport", new { area = "" }, new { @class = "btn btn-primary" })



                    </div>
                </div>
            </div>



            <div class="col">

                <div class="card" style="width: 18rem; color: ghostwhite">

                    <div class="card-body" style="background-color:rgb(192, 78, 237)">
                        <h5 class="card-title">Development And Research Management Details</h5>


                        @*linkName   ActionName    Controller*@
                        @Html.ActionLink("Development And Research", "Index", "DResearch", new { area = "" }, new { @class = "btn btn-primary" })

                    </div>
                </div>
            </div>




        </div>
    </div>


    @*2nd Row Container*@


    <div class="container mt-5">
        <div class="row">

            <div class="col">

                <div class="card" style="width: 18rem; color: ghostwhite">

                    <div class="card-body" style="background-color:rgb(192, 78, 237)">
                        <h5 class="card-title">Ecomarce Management Details</h5>


                        @*linkName   ActionName    Controller*@
                        @Html.ActionLink("Ecommerce Info", "Index", "ECommerce", new { area = "" }, new { @class = "btn btn-primary" })



                    </div>
                </div>
            </div>


            <div class="col">

                <div class="card" style="width: 18rem; color: ghostwhite">

                    <div class="card-body" style="background-color:rgb(192, 78, 237)">
                        <h5 class="card-title"> Environment Analyses Details</h5>
                        @*linkName   ActionName    Controller*@
                        @Html.ActionLink("Environment Info", "Index", "Environmental", new { area = "" }, new { @class = "btn btn-primary" })



                    </div>
                </div>
            </div>



            <div class="col">

                <div class="card" style="width: 18rem; color: ghostwhite">

                    <div class="card-body" style="background-color:rgb(192, 78, 237)">
                        <h5 class="card-title">Financial Management Details</h5>
                        @*linkName   ActionName    Controller*@
                        @Html.ActionLink("Financial Info", "Index", "Finance", new { area = "" }, new { @class = "btn btn-primary" })
                    </div>
                </div>
            </div>




        </div>
    </div>




    @*3rd  Row Container*@


    <div class="container mt-5">
        <div class="row">

            <div class="col">

                <div class="card" style="width: 18rem; color: ghostwhite">

                    <div class="card-body" style="background-color:rgb(192, 78, 237)">
                        <h5 class="card-title">Human Resources Details</h5>


                        @*linkName   ActionName    Controller*@
                        @Html.ActionLink("H R Details", "Index", "HResource", new { area = "" }, new { @class = "btn btn-primary" })



                    </div>
                </div>
            </div>


            <div class="col">

                <div class="card" style="width: 18rem; color: ghostwhite">
                    @*<img src="~/Content/img/subject.jpg" class="card-img-top" alt="...">*@
                    <div class="card-body" style="background-color:rgb(192, 78, 237)">
                        <h5 class="card-title"> Inventory System Details</h5>
                        @*linkName   ActionName    Controller*@
                        @Html.ActionLink("Inventory Info", "Index", "Inventory", new { area = "" }, new { @class = "btn btn-primary" })



                    </div>
                </div>
            </div>



            <div class="col">

                <div class="card" style="width: 18rem; color: ghostwhite">

                    <div class="card-body" style="background-color:rgb(192, 78, 237)">
                        <h5 class="card-title">Logistics System Details</h5>
                        @*linkName   ActionName    Controller*@
                        @Html.ActionLink("Logistics Info", "Index", "Logistics", new { area = "" }, new { @class = "btn btn-primary" })
                    </div>
                </div>
            </div>




        </div>
    </div>





    @*4th  Row Container*@


    <div class="container mt-5 mb-5">
        <div class="row">

            <div class="col">

                <div class="card" style="width: 18rem; color: ghostwhite">

                    <div class="card-body" style="background-color:rgb(192, 78, 237)">
                        <h5 class="card-title">Marketing Management System Details</h5>


                        @*linkName   ActionName    Controller*@
                        @Html.ActionLink("Marketing Management ", "Index", "Marketing", new { area = "" }, new { @class = "btn btn-primary" })



                    </div>
                </div>
            </div>


            <div class="col">

                <div class="card" style="width: 18rem; color: ghostwhite">

                    <div class="card-body" style="background-color:rgb(192, 78, 237)">
                        <h5 class="card-title"> Production Management Information</h5>
                        @*linkName   ActionName    Controller*@
                        @Html.ActionLink("Production Info", "Index", "Production", new { area = "" }, new { @class = "btn btn-primary" })



                    </div>
                </div>
            </div>



            <div class="col">

                <div class="card" style="width: 18rem; color: ghostwhite">

                    <div class="card-body" style="background-color:rgb(192, 78, 237)">
                        <h5 class="card-title">Quality Checking Details</h5>
                        @*linkName   ActionName    Controller*@
                        @Html.ActionLink("Quality Checking Info", "Index", "Quality", new { area = "" }, new { @class = "btn btn-primary" })
                    </div>
                </div>
            </div>




        </div>
    </div>

    <div class="container mt-5">
        <div class="row">

            <div class="col">

                <div class="card" style="width: 18rem; color: ghostwhite">

                    <div class="card-body" style="background-color:rgb(192, 78, 237)">
                        <h5 class="card-title">Get In Touch  Details</h5>


                        @*linkName   ActionName    Controller*@
                        @Html.ActionLink("Contact us Info", "Index", "QuickContact", new { area = "" }, new { @class = "btn btn-primary" })



                    </div>
                </div>
            </div>


            <div class="col">

                <div class="card" style="width: 18rem; color: ghostwhite">

                    <div class="card-body" style="background-color:rgb(192, 78, 237)">
                        <h5 class="card-title"> Registered User Details</h5>
                        @*linkName   ActionName    Controller*@
                        @Html.ActionLink("Register Info", "Index", "Register", new { area = "" }, new { @class = "btn btn-primary" })



                    </div>
                </div>
            </div>



            <div class="col">

                <div class="card" style="width: 18rem; color: ghostwhite">

                    <div class="card-body" style="background-color:rgb(192, 78, 237)">
                        <h5 class="card-title">Production Sales Details</h5>
                        @*linkName   ActionName    Controller*@
                        @Html.ActionLink("Sales Info", "Index", "Sales", new { area = "" }, new { @class = "btn btn-primary" })
                    </div>
                </div>
            </div>




        </div>
    </div>












    <div class="container mt-5">
        <div class="row">

            <div class="col">

                <div class="card" style="width: 18rem; color: ghostwhite">

                    <div class="card-body" style="background-color:rgb(192, 78, 237)">
                        <h5 class="card-title">Supplier Relationship Details</h5>


                        @*linkName   ActionName    Controller*@
                        @Html.ActionLink("Relationship Info", "Index", "SRelationShip", new { area = "" }, new { @class = "btn btn-primary" })



                    </div>
                </div>
            </div>


            <div class="col">

                <div class="card" style="width: 18rem; color: ghostwhite">

                    <div class="card-body" style="background-color:rgb(192, 78, 237)">
                        <h5 class="card-title">Production Supplier  Details</h5>
                        @*linkName   ActionName    Controller*@
                        @Html.ActionLink("Supplier Info", "Index", "Supplier", new { area = "" }, new { @class = "btn btn-primary" })



                    </div>
                </div>
            </div>



            <!--<div class="col">

                <div class="card" style="width: 18rem; color: ghostwhite">

                    <div class="card-body" style="background-color:rgb(192, 78, 237)">
                        <h5 class="card-title">Event Information Details</h5>-->
            @*linkName   ActionName    Controller*@
            <!--@Html.ActionLink("Sales Info", "Index", "Sales", new { area = "" }, new { @class = "btn btn-primary" })
                    </div>
                </div>
            </div>-->




        </div>
    </div>





</section>

DryFruitSelling/Views/HomePage/ContactPage.cshtml
@model DryFruitSelling.Models.contactus
@{
    ViewBag.Title = "ContactPage";
}


@if (TempData["Success"] != null)
{
    <script>alert("@TempData["Success"]")</script>
}




@if (TempData["Error"] != null)
{
    <script>alert("@TempData["Error"]")</script>
}


<main class="flex-shrink-0">

    <!-- Page content-->
    <section class="py-5">
        <div class="container px-5">
            <!-- Contact form-->
            <div class="bg-light rounded-3 py-5 px-4 px-md-5 mb-5">
                <div class="text-center mb-5">
                    <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-envelope"></i></div>
                    <h1 class="fw-bolder">Get in touch</h1>
                    <p class="lead fw-normal text-muted mb-0">We'd love to hear from you</p>
                </div>
                <div class="row gx-5 justify-content-center">
                    <div class="col-lg-8 col-xl-6">


                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                                <div class="form-group mt-2 mb-3">
                                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter your name..." } })
                                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <!-- Name input-->
                                <!-- Email address input-->


                                <div class="form-group mb-3">
                                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", placeholder = "name@example.com" } })
                                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <!-- Phone number input-->

                                <div class="form-group mb-3">
                                    @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control", placeholder = "(123) 456-7890" } })
                                        @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <!-- Message input-->


                                <div class="form-group mb-3">
                                    @Html.LabelFor(model => model.Message, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.TextAreaFor(model => model.Message, new { @class = "form-control", placeholder = "Enter your message here..." })
                                        @Html.ValidationMessageFor(model => model.Message, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <!-- Submit success message-->
                                <!---->
                                <!-- This is what your users will see when the form-->
                                <!-- has successfully submitted-->
                                <div class="d-none" id="submitSuccessMessage">
                                    <div class="text-center mb-3">
                                        <div class="fw-bolder">Form submission successful!</div>
                                        To activate this form, sign up at
                                        <br />
                                        <a href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                                    </div>
                                </div>


                                <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3">Error sending message!</div></div>
                                <!-- Submit Button-->

                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10 d-grid">
                                        <input type="submit" value="Send" class="class=" btn btn-primary btn-lg disabled" />
                                    </div>
                                </div>

                            </div>
                        }

                    </div>
                </div>
            </div>



            <!-- Contact cards-->
            <div class="row gx-5 row-cols-2 row-cols-lg-4 py-5">
                <div class="col">
                    <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-chat-dots"></i></div>
                    <div class="h5 mb-2">Chat with us</div>
                    <p class="text-muted mb-0">Chat live with one of our support specialists.</p>
                </div>
                <div class="col">
                    <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-people"></i></div>
                    <div class="h5">Ask the community</div>
                    <p class="text-muted mb-0">Explore our community forums and communicate with other users.</p>
                </div>
                <div class="col">
                    <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-question-circle"></i></div>
                    <div class="h5">Support center</div>
                    <p class="text-muted mb-0">Browse FAQ's and support articles to find solutions.</p>
                </div>
                <div class="col">
                    <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-telephone"></i></div>
                    <div class="h5">Call us</div>
                    <p class="text-muted mb-0">Call us during normal business hours at (555) 892-9403.</p>
                </div>
            </div>





        </div>
    </section>
</main>