DryFruitSelling/Models/inventory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DryFruitSelling.Models
{
    public class inventory
    {
        
        public int id {  get; set; }

        [Required]
        [Display(Name ="Inventory ID")]
        public string InventoryID { get; set; }


        [Required]
        [Display(Name = "Fruit Type")]
        public string FruitType { get; set; }


        [Required]
        [Display(Name = "Quantity")]
        public int Quantity { get; set; }


        [Required]
        [Display(Name = "Preservation Status")]
        public string PreservationStatus {  get; set; }



        [Required]
        [Display(Name = "Expiration Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]

        public DateTime ExpirationDate {  get; set; }


    }
}

DryFruitSelling/Controllers/InventoryController.cs
using DryFruitSelling.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DryFruitSelling.Controllers
{
    public class InventoryController : Controller
    {


        string strcon = ConfigurationManager.ConnectionStrings["MyConnection"].ConnectionString;

        // GET: Inventory
        public ActionResult Index()
        {
            List<inventory> inventory = new List<inventory>();

            using(SqlConnection conn = new SqlConnection(strcon))
            {
                conn.Open();
                SqlCommand cmd = new SqlCommand("sp_vwall_inventory", conn);
                cmd.CommandType = System.Data.CommandType.StoredProcedure;

                SqlDataReader sdr = cmd.ExecuteReader();

                while(sdr.Read())
                {
                    inventory.Add(new inventory
                    { 
                    
                    id=Convert.ToInt32(sdr["id"]),
                        InventoryID = sdr["InventoryID"].ToString(),
                        FruitType = sdr["FruitType"].ToString(),
                        Quantity = Convert.ToInt32(sdr["Quantity"]),
                        PreservationStatus = sdr["PreservationStatus"].ToString(),
                        ExpirationDate = Convert.ToDateTime(sdr["ExpirationDate"])


                    });
                }
                conn.Close();
            }


            return View(inventory);
        }

        // GET: Inventory/Details/5
        public ActionResult Details(int id)
        {
            inventory inventory = new inventory();

            using (SqlConnection conn = new SqlConnection(strcon))
            {
                conn.Open();
                SqlCommand cmd = new SqlCommand("sp_getone_inventory", conn);
                cmd.CommandType = System.Data.CommandType.StoredProcedure;

                cmd.Parameters.AddWithValue("@id",id);

                SqlDataReader sdr = cmd.ExecuteReader();

                while (sdr.Read())
                {
                    inventory = new inventory
                    {

                        id = Convert.ToInt32(sdr["id"]),
                        InventoryID = sdr["InventoryID"].ToString(),
                        FruitType = sdr["FruitType"].ToString(),
                        Quantity = Convert.ToInt32(sdr["Quantity"]),
                        PreservationStatus = sdr["PreservationStatus"].ToString(),
                        ExpirationDate = Convert.ToDateTime(sdr["ExpirationDate"])


                    };
                }
                conn.Close();
            }


            return View(inventory);
        }

        // GET: Inventory/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Inventory/Create
        [HttpPost]
        public ActionResult Create(inventory inventory)
        {
            try
            {
                // TODO: Add insert logic here


                using(SqlConnection conn = new SqlConnection(strcon))
                {
                    conn.Open();
                    SqlCommand cmd = new SqlCommand("sp_insert_inventory", conn);
                    cmd.CommandType = System.Data.CommandType.StoredProcedure;

                    cmd.Parameters.AddWithValue("@InventoryID", inventory.InventoryID);
                    cmd.Parameters.AddWithValue("@FruitType", inventory.FruitType);

                    cmd.Parameters.AddWithValue("@Quantity", inventory.Quantity);


                    cmd.Parameters.AddWithValue("@PreservationStatus", inventory.PreservationStatus);
                    cmd.Parameters.AddWithValue("@ExpirationDate", inventory.ExpirationDate);
                    
                    int i = cmd.ExecuteNonQuery();
                    if (i > 0)
                    {
                        TempData["success"] = "Data send successfully!";

                    }
                    else
                    {
                        TempData["error"] = "Data send failure!";
                    }
                }


                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Inventory/Edit/5
        public ActionResult Edit(int id)
        {
            inventory inventory = new inventory();

            using (SqlConnection conn = new SqlConnection(strcon))
            {
                conn.Open();
                SqlCommand cmd = new SqlCommand("sp_getone_inventory", conn);
                cmd.CommandType = System.Data.CommandType.StoredProcedure;

                cmd.Parameters.AddWithValue("@id", id);

                SqlDataReader sdr = cmd.ExecuteReader();

                while (sdr.Read())
                {
                    inventory = new inventory
                    {

                        id = Convert.ToInt32(sdr["id"]),
                        InventoryID = sdr["InventoryID"].ToString(),
                        FruitType = sdr["FruitType"].ToString(),
                        Quantity = Convert.ToInt32(sdr["Quantity"]),
                        PreservationStatus = sdr["PreservationStatus"].ToString(),
                        ExpirationDate = Convert.ToDateTime(sdr["ExpirationDate"])


                    };
                }
                conn.Close();
            }


            return View(inventory);
        }

        // POST: Inventory/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, inventory inventory)
        {
            try
            {
                // TODO: Add update logic here

                using (SqlConnection conn = new SqlConnection(strcon))
                {
                    conn.Open();
                    SqlCommand cmd = new SqlCommand("sp_update_inventory", conn);
                    cmd.CommandType = System.Data.CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@id",id);

                    cmd.Parameters.AddWithValue("@InventoryID", inventory.InventoryID);
                    cmd.Parameters.AddWithValue("@FruitType", inventory.FruitType);

                    cmd.Parameters.AddWithValue("@Quantity", inventory.Quantity);

                    cmd.Parameters.AddWithValue("@PreservationStatus", inventory.PreservationStatus);
                    cmd.Parameters.AddWithValue("@ExpirationDate", inventory.ExpirationDate);

                    int i = cmd.ExecuteNonQuery();
                    if (i > 0)
                    {
                        TempData["success"] = "Data updated successfully!";

                    }
                    else
                    {
                        TempData["error"] = "Data updated failure!";
                    }
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Inventory/Delete/5
        public ActionResult Delete(int id)
        {
            inventory inventory = new inventory();

            using (SqlConnection conn = new SqlConnection(strcon))
            {
                conn.Open();
                SqlCommand cmd = new SqlCommand("sp_getone_inventory", conn);
                cmd.CommandType = System.Data.CommandType.StoredProcedure;

                cmd.Parameters.AddWithValue("@id", id);

                SqlDataReader sdr = cmd.ExecuteReader();

                while (sdr.Read())
                {
                    inventory = new inventory
                    {

                        id = Convert.ToInt32(sdr["id"]),
                        InventoryID = sdr["InventoryID"].ToString(),
                        FruitType = sdr["FruitType"].ToString(),
                        Quantity = Convert.ToInt32(sdr["Quantity"]),
                        PreservationStatus = sdr["PreservationStatus"].ToString(),
                        ExpirationDate = Convert.ToDateTime(sdr["ExpirationDate"])


                    };
                }
                conn.Close();
            }


            return View(inventory);
        }

        // POST: Inventory/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                using (SqlConnection conn = new SqlConnection(strcon))
                {
                    conn.Open();
                    SqlCommand cmd = new SqlCommand("sp_delete_inventory", conn);
                    cmd.CommandType = System.Data.CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@id", id);

                    
                    int i = cmd.ExecuteNonQuery();
                    if (i > 0)
                    {
                        TempData["success"] = "Data Deleted successfully!";

                    }
                    else
                    {
                        TempData["error"] = "Data Deleted failure!";
                    }
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }




        public ActionResult Search()
        {
            List<inventory> inventory = new List<inventory>();

            using (SqlConnection conn = new SqlConnection(strcon))
            {
                conn.Open();
                SqlCommand cmd = new SqlCommand("sp_vwall_inventory", conn);
                cmd.CommandType = System.Data.CommandType.StoredProcedure;

                SqlDataReader sdr = cmd.ExecuteReader();

                while (sdr.Read())
                {
                    inventory.Add(new inventory
                    {

                        id = Convert.ToInt32(sdr["id"]),

DryFruitSelling/Views/Inventory/Create.cshtml
@model DryFruitSelling.Models.inventory

@{
    ViewBag.Title = "Create";
}

<main class="flex-shrink-0">
    <section class="py-5">
        <div class="container px-5">
            <!-- Contact form-->
            <div class="bg-light rounded-3 py-5 px-4 px-md-5 mb-5">
                <div class="text-center mb-5">
                    <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-person-circle"></i></div>


                    <h1 class="fw-bolder">Create Inventory System Details</h1>

                </div>
                <div class="row gx-5 justify-content-center">
                    <div class="col-lg-8 col-xl-6">


                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">

                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })




                                <div class="form-group mt-2 mb-3">
                                    @Html.LabelFor(model => model.InventoryID, htmlAttributes: new { @class = "control-label" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.InventoryID, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.InventoryID, "", new { @class = "text-danger" })
                                    </div>
                                </div>




                                <div class="form-group mb-3">
                                    @Html.LabelFor(model => model.FruitType, htmlAttributes: new { @class = "control-label" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.FruitType, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.FruitType, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group mb-3">
                                    @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group mb-3">
                                    @Html.LabelFor(model => model.PreservationStatus, htmlAttributes: new { @class = "control-label" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.PreservationStatus, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.PreservationStatus, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group mb-3">
                                    @Html.LabelFor(model => model.ExpirationDate, htmlAttributes: new { @class = "control-label" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.ExpirationDate, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.ExpirationDate, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group mb-3">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="submit" value="Create" class="btn btn-primary" />
                                    </div>
                                </div>
                            </div>
                        }

                        <div>
                            @Html.ActionLink("Back to List", "Index")
                        </div>





                    </div>
                </div>
            </div>
        </div>
    </section>
</main>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DryFruitSelling/Views/Inventory/Delete.cshtml
@model DryFruitSelling.Models.inventory

@{
    ViewBag.Title = "Delete";
}

<main class="flex-shrink-0">
    <section class="py-5">
        <div class="container px-5">
            <!-- Contact form-->
            <div class="bg-light rounded-3 py-5 px-4 px-md-5 mb-5">
                <div class="text-center mb-5">
                    <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-person-circle"></i></div>


                    <h1 class="fw-bolder">Delete Inventory System Details</h1>

                </div>
                <div class="row gx-5 justify-content-center">
                    <div class="col-lg-8 col-xl-6">

                        <h3>Are you sure you want to delete this?</h3>
                        <div>

                            <dl class="dl-horizontal">

                                <dt>
                                    @Html.DisplayNameFor(model => model.InventoryID)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.InventoryID)
                                </dd>


                                <dt>
                                    @Html.DisplayNameFor(model => model.FruitType)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.FruitType)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.Quantity)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Quantity)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.PreservationStatus)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.PreservationStatus)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.ExpirationDate)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.ExpirationDate)
                                </dd>

                            </dl>

                            @using (Html.BeginForm())
                            {
                                @Html.AntiForgeryToken()

                                <div class="form-actions no-color">
                                    <input type="submit" value="Delete" class="btn btn-default" /> |
                                    @Html.ActionLink("Back to List", "Index")
                                </div>
                            }
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
</main>

DryFruitSelling/Views/Inventory/Details.cshtml
@model DryFruitSelling.Models.inventory

@{
    ViewBag.Title = "Details";
}


<main class="flex-shrink-0">
    <section class="py-5">
        <div class="container px-5">
            <!-- Contact form-->
            <div class="bg-light rounded-3 py-5 px-4 px-md-5 mb-5">
                <div class="text-center mb-5">
                    <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-person-circle"></i></div>


                    <h1 class="fw-bolder">Delete Inventory System Details</h1>

                </div>
                <div class="row gx-5 justify-content-center">
                    <div class="col-lg-8 col-xl-6">


                        <div>
                            <dl class="dl-horizontal">



                                <dt>
                                    @Html.DisplayNameFor(model => model.InventoryID)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.InventoryID)
                                </dd>




                                <dt>
                                    @Html.DisplayNameFor(model => model.FruitType)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.FruitType)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.Quantity)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Quantity)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.PreservationStatus)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.PreservationStatus)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.ExpirationDate)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.ExpirationDate)
                                </dd>

                            </dl>
                        </div>
                        <p>
                            @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
                            @Html.ActionLink("Back to List", "Index")
                        </p>

                    </div>
                </div>
            </div>
        </div>
    </section>
</main>

DryFruitSelling/Views/Inventory/Edit.cshtml
@model DryFruitSelling.Models.inventory

@{
    ViewBag.Title = "Edit";
}


<main class="flex-shrink-0">
    <section class="py-5">
        <div class="container px-5">
            <!-- Contact form-->
            <div class="bg-light rounded-3 py-5 px-4 px-md-5 mb-5">
                <div class="text-center mb-5">
                    <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-person-circle"></i></div>


                    <h1 class="fw-bolder">Edit Inventory System Details</h1>

                </div>
                <div class="row gx-5 justify-content-center">
                    <div class="col-lg-8 col-xl-6">


                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">

                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                @Html.HiddenFor(model => model.id)

                                @*@Html.HiddenFor(model => model.InventoryID)*@



                                <div class="form-group mt-2 mb-3">
                                    @Html.LabelFor(model => model.InventoryID, htmlAttributes: new { @class = "control-label" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.InventoryID, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.InventoryID, "", new { @class = "text-danger" })
                                    </div>
                                </div>



                                <div class="form-group mb-3">
                                    @Html.LabelFor(model => model.FruitType, htmlAttributes: new { @class = "control-label" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.FruitType, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.FruitType, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group mb-3">
                                    @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group mb-3">
                                    @Html.LabelFor(model => model.PreservationStatus, htmlAttributes: new { @class = "control-label" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.PreservationStatus, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.PreservationStatus, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group mb-3">
                                    @Html.LabelFor(model => model.ExpirationDate, htmlAttributes: new { @class = "control-label" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.ExpirationDate, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.ExpirationDate, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group mb-3">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="submit" value="Save" class="btn btn-primary" />
                                    </div>
                                </div>
                            </div>
                        }

                        <div>
                            @Html.ActionLink("Back to List", "Index")
                        </div>







                    </div>
                </div>
            </div>
        </div>
    </section>
</main>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DryFruitSelling/Views/Inventory/Index.cshtml
@model IEnumerable<DryFruitSelling.Models.inventory>

@{
    ViewBag.Title = "Index";
}






@if (TempData["Success"] != null)
{
    <script style="color:green">
                        alert("@TempData["Success"]")

    </script>
}

@if (TempData["Error"] != null)
{
    <script style="color:indianred">
                        alert("@TempData["Error"]")

    </script>
}



<div class="p-3 mb-2 bg-secondary text-white text-center mt-5 mb-5">
    Inventory System Record Details

</div>




@if (TempData["Success"] != null)
{
    <script style="color:green">
                        alert("@TempData["Success"]")

    </script>
}

@if (TempData["Error"] != null)
{
    <script style="color:indianred">
                        alert("@TempData["Error"]")

    </script>
}









<p>
    @Html.ActionLink("Create New", "Create")

    &nbsp;&nbsp;&nbsp;&nbsp;

    @Html.ActionLink("Search", "Search")
</p>
<table class="table">
    <tr>


        <th>
            @Html.DisplayNameFor(model => model.InventoryID)
        </th>






        <th>
            @Html.DisplayNameFor(model => model.FruitType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PreservationStatus)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ExpirationDate)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>


            <td>
                @Html.DisplayFor(modelItem => item.InventoryID)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.FruitType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PreservationStatus)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExpirationDate)
            </td>
            <td>
                <div class="btn-group" role="group" aria-label="Basic mixed styles example">


                    @using (Html.BeginForm("Edit", "Inventory", new { id = item.id }, FormMethod.Get, new { @class = "form-inline" }))
                    {
                        <button class="btn btn-warning" type="submit">Edit</button>
                    }

                    &nbsp;

                    @using (Html.BeginForm("Details", "Inventory", new { id = item.id }, FormMethod.Get, new { @class = "form-inline" }))
                    {
                        <button class="btn btn-primary" type="submit">Details</button>
                    }

                    &nbsp;

                    @using (Html.BeginForm("Delete", "Inventory", new { id = item.id }, FormMethod.Get, new { @class = "form-inline" }))
                    {
                        <button class="btn btn-danger" type="submit">Delete</button>
                    }




                </div>
            </td>
        </tr>
    }

</table>

DryFruitSelling/Views/Inventory/Search.cshtml
@model IEnumerable<DryFruitSelling.Models.inventory>

@{
    ViewBag.Title = "Search";
}






<div class="p-3 mb-2 bg-secondary text-white text-center mt-5 mb-5">
    Inventory System Record Details

</div>


<p>
    @Html.ActionLink("Go To Index", "Index")
</p>




@using (Html.BeginForm())
{

    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="offset-5 text-dark mb-5">
        <div class="form-group">
            <label for="Search">Search Inventory Details</label>
            <input type="search" class="form-control" name="Search" placeholder="Search Inventory Details" />
        </div>


        <div class="form-group mt-2">

            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Search" class="btn btn-success" />
            </div>


        </div>

    </div>
}









<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FruitType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PreservationStatus)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ExpirationDate)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FruitType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PreservationStatus)
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.ExpirationDate)*@

                @item.ExpirationDate.ToString("dd/MM/yyyy")

            </td>
            <td>






@*                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })*@
            </td>
        </tr>
    }

</table>